import type { NetworkData, WarehouseKpis } from "./types"

export const initialNetworkData: NetworkData = {
  plant: {
    name: "Kohler Plant - Kohler, WI",
  },
  centralWarehouse: {
    name: "Ferguson Master DC - Newport News, VA",
    orderQuantity: 12000,
    safetyStock: 2000,
    leadTime: 2,
    periods: [
      {
        periodUsage: 100,
        grossRequirements: 100,
        beginningInventory: 150,
        scheduledReceipts: 0,
        netRequirements: 20,
        plannedReceipts: 0,
        endingInventory: 50,
        plannedOrder: 12000,
      },
      {
        periodUsage: 20,
        grossRequirements: 20,
        beginningInventory: 50,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 30,
        plannedOrder: null,
      },
      {
        periodUsage: 50,
        grossRequirements: 50,
        beginningInventory: 30,
        scheduledReceipts: 0,
        netRequirements: 20,
        plannedReceipts: 12000,
        endingInventory: 11980,
        plannedOrder: null,
      },
      {
        periodUsage: 30,
        grossRequirements: 30,
        beginningInventory: 11980,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 11950,
        plannedOrder: null,
      },
      {
        periodUsage: 100,
        grossRequirements: 100,
        beginningInventory: 11950,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 11850,
        plannedOrder: null,
      },
      {
        periodUsage: 0,
        grossRequirements: 0,
        beginningInventory: 11850,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 11850,
        plannedOrder: null,
      },
      {
        periodUsage: 100,
        grossRequirements: 100,
        beginningInventory: 11850,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 11750,
        plannedOrder: null,
      },
      {
        periodUsage: 0,
        grossRequirements: 0,
        beginningInventory: 11750,
        scheduledReceipts: 0,
        netRequirements: null,
        plannedReceipts: 0,
        endingInventory: 11750,
        plannedOrder: null,
      },
    ],
  },
  regionalWarehouses: [
    {
      name: "Ferguson DC - Atlanta, GA",
      orderQuantity: 4500,
      safetyStock: 800,
      leadTime: 1,
      retailers: ["Ferguson Branch - Charlotte", "Ferguson Branch - Orlando", "Ferguson Branch - Miami"],
      periods: [
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 50,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 25,
          plannedOrder: 4500,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 25,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 4500,
          endingInventory: 4500,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 4500,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 4475,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 4475,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 4450,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 4450,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 4425,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 4425,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 4400,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 4400,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 4375,
          plannedOrder: null,
        },
        {
          periodUsage: 25,
          grossRequirements: 40,
          beginningInventory: 4375,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 4350,
          plannedOrder: null,
        },
      ],
    },
    {
      name: "Ferguson DC - Dallas, TX",
      orderQuantity: 3200,
      safetyStock: 600,
      leadTime: 1,
      retailers: ["Ferguson Branch - Houston", "Ferguson Branch - San Antonio", "Ferguson Branch - Austin"],
      periods: [
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 20,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 10,
          plannedOrder: 3200,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 10,
          scheduledReceipts: 0,
          netRequirements: 10,
          plannedReceipts: 3200,
          endingInventory: 3200,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 3200,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 3190,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 3190,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 3180,
          plannedOrder: null,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 3180,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 3160,
          plannedOrder: null,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 3160,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 3140,
          plannedOrder: null,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 3140,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 3120,
          plannedOrder: null,
        },
        {
          periodUsage: 20,
          grossRequirements: 30,
          beginningInventory: 3120,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 3100,
          plannedOrder: null,
        },
      ],
    },
    {
      name: "Ferguson DC - Chicago, IL",
      orderQuantity: 2800,
      safetyStock: 500,
      leadTime: 1,
      retailers: ["Ferguson Branch - Milwaukee", "Ferguson Branch - Indianapolis", "Ferguson Branch - Minneapolis"],
      periods: [
        {
          periodUsage: 5,
          grossRequirements: 15,
          beginningInventory: 15,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 10,
          plannedOrder: 2800,
        },
        {
          periodUsage: 15,
          grossRequirements: 25,
          beginningInventory: 10,
          scheduledReceipts: 0,
          netRequirements: 15,
          plannedReceipts: 2800,
          endingInventory: 2795,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 2795,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 2785,
          plannedOrder: null,
        },
        {
          periodUsage: 10,
          grossRequirements: 20,
          beginningInventory: 2785,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 2775,
          plannedOrder: null,
        },
        {
          periodUsage: 0,
          grossRequirements: 10,
          beginningInventory: 2775,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 2775,
          plannedOrder: null,
        },
        {
          periodUsage: 15,
          grossRequirements: 25,
          beginningInventory: 2775,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 2760,
          plannedOrder: null,
        },
        {
          periodUsage: 0,
          grossRequirements: 10,
          beginningInventory: 2760,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 2760,
          plannedOrder: null,
        },
        {
          periodUsage: 15,
          grossRequirements: 25,
          beginningInventory: 2760,
          scheduledReceipts: 0,
          netRequirements: null,
          plannedReceipts: 0,
          endingInventory: 2745,
          plannedOrder: null,
        },
      ],
    },
  ],
}

export const initialKpis: WarehouseKpis = {
  "Ferguson Master DC - Newport News, VA": {
    serviceLevel: 98.5,
    inventoryTurnover: 3.2,
    averageInventory: 8926.25,
    stockoutPeriods: 0,
    orderFrequency: 12.5, // percentage of periods with orders
  },
  "Ferguson DC - Atlanta, GA": {
    serviceLevel: 100,
    inventoryTurnover: 4.0,
    averageInventory: 3375.0,
    stockoutPeriods: 0,
    orderFrequency: 12.5,
  },
  "Ferguson DC - Dallas, TX": {
    serviceLevel: 100,
    inventoryTurnover: 4.8,
    averageInventory: 2525.0,
    stockoutPeriods: 0,
    orderFrequency: 12.5,
  },
  "Ferguson DC - Chicago, IL": {
    serviceLevel: 100,
    inventoryTurnover: 3.5,
    averageInventory: 2325.63,
    stockoutPeriods: 0,
    orderFrequency: 12.5,
  },
}
