"use client"

import VRProductDashboard from "@/components/controlKpi/vr-product-dashboard"
import { useParams } from "next/navigation"

function getProductData(slug: string) {
  const finishedGoodsData = [
    {
      distributionCenter: "7-Eleven DC - Dallas, TX",
      productModel: "Coca-Cola 12pk Variety Pack",
      sku: "CC-001",
      currentStock: 12450,
      forecastDemand: 18000,
      retailPartner: "Store Manager Accounts",
      region: "Mid-Atlantic",
      alertType: "Stock Shortage",
      daysOfInventory: 23,
      lastShipment: "Jan 14, 2025",
      nextShipment: "Jan 20, 2025",
      salesVelocity: "+15%",
      retailPrice: "$499.99",
      priority: "high",
    },
    {
      distributionCenter: "7-Eleven DC - Dallas, TX",
      productModel: "PepsiCo Variety Pack",
      sku: "PC-001",
      currentStock: 8920,
      forecastDemand: 7500,
      retailPartner: "Franchise Operator Accounts",
      region: "South Central",
      alertType: "Optimal Stock",
      daysOfInventory: 47,
      lastShipment: "Jan 12, 2025",
      nextShipment: "Jan 25, 2025",
      salesVelocity: "+8%",
      retailPrice: "$649.99",
      priority: "normal",
    },
    {
      distributionCenter: "7-Eleven DC - Mocksville, NC",
      productModel: "Hershey Snack Assortment",
      sku: "HS-001",
      currentStock: 2340,
      forecastDemand: 8500,
      retailPartner: "Store Associate Accounts",
      region: "Southeast",
      alertType: "Critical Shortage",
      daysOfInventory: 12,
      lastShipment: "Jan 10, 2025",
      nextShipment: "Jan 18, 2025",
      salesVelocity: "+22%",
      retailPrice: "$999.99",
      priority: "critical",
    },
    {
      distributionCenter: "7-Eleven DC - Denver, CO",
      productModel: "7-Select Hot Coffee Blend",
      sku: "7S-COF-001",
      currentStock: 15680,
      forecastDemand: 12000,
      retailPartner: "Franchise Operator Accounts",
      region: "Mountain West",
      alertType: "Overstock",
      daysOfInventory: 65,
      lastShipment: "Jan 08, 2025",
      nextShipment: "Feb 01, 2025",
      salesVelocity: "-3%",
      retailPrice: "$1,549.99",
      priority: "low",
    },
    {
      distributionCenter: "7-Eleven DC - Phoenix, AZ",
      productModel: "Monster / Red Bull Energy Drinks",
      sku: "ED-001",
      currentStock: 4560,
      forecastDemand: 9200,
      retailPartner: "Franchise Operator Accounts",
      region: "Southwest",
      alertType: "Stock Shortage",
      daysOfInventory: 18,
      lastShipment: "Jan 13, 2025",
      nextShipment: "Jan 22, 2025",
      salesVelocity: "+28%",
      retailPrice: "$2,899.00",
      priority: "high",
    },
    {
      distributionCenter: "7-Eleven DC - Chicago, IL",
      productModel: "Marlboro Cigarettes Carton",
      sku: "TC-001",
      currentStock: 3420,
      forecastDemand: 4500,
      retailPartner: "Core-Mark Distribution",
      region: "Midwest",
      alertType: "Low Stock",
      daysOfInventory: 28,
      lastShipment: "Jan 11, 2025",
      nextShipment: "Jan 24, 2025",
      salesVelocity: "+12%",
      retailPrice: "$629.99",
      priority: "normal",
    },
    {
      distributionCenter: "7-Eleven DC - Atlanta, GA",
      productModel: "Mondelēz Snack Variety",
      sku: "MDZ-001",
      currentStock: 1890,
      forecastDemand: 2800,
      retailPartner: "Store Manager Accounts",
      region: "Southeast",
      alertType: "Stock Shortage",
      daysOfInventory: 24,
      lastShipment: "Jan 09, 2025",
      nextShipment: "Jan 19, 2025",
      salesVelocity: "+18%",
      retailPrice: "$349.99",
      priority: "high",
    },
    {
      distributionCenter: "7-Eleven DC - Sacramento, CA",
      productModel: "Frozen Treats Variety Pack",
      sku: "FZ-001",
      currentStock: 7240,
      forecastDemand: 6800,
      retailPartner: "Franchise Operator Accounts",
      region: "West Coast",
      alertType: "Optimal Stock",
      daysOfInventory: 42,
      lastShipment: "Jan 15, 2025",
      nextShipment: "Jan 28, 2025",
      salesVelocity: "+5%",
      retailPrice: "$39.99",
      priority: "normal",
    },
  ]

  return finishedGoodsData.find((item) => slug.includes(item.sku)) || finishedGoodsData[0]
}

export default function ProductDetailPage() {
  const params = useParams()
  const slug = params.slug as string
  const productData = getProductData(slug)

  return <VRProductDashboard productData={productData} />
}
