"use client"

import VRProductDashboard from "@/components/controlKpi/vr-product-dashboard"
import { useParams } from "next/navigation"

function getProductData(slug: string) {
  const finishedGoodsData = [
    {
      distributionCenter: "Ferguson DC - Newport News, VA",
      productModel: "Bradford White 40-gal Water Heater",
      sku: "FRG-WH-4050",
      currentStock: 12450,
      forecastDemand: 18000,
      retailPartner: "Plumbing Contractor Accounts",
      region: "Mid-Atlantic",
      alertType: "Stock Shortage",
      daysOfInventory: 23,
      lastShipment: "Jan 14, 2025",
      nextShipment: "Jan 20, 2025",
      salesVelocity: "+15%",
      retailPrice: "$499.99",
      priority: "high",
    },
    {
      distributionCenter: "Ferguson DC - Dallas, TX",
      productModel: "Rheem 50-gal Electric Water Heater",
      sku: "FRG-WH-5060E",
      currentStock: 8920,
      forecastDemand: 7500,
      retailPartner: "HVAC Contractor Accounts",
      region: "South Central",
      alertType: "Optimal Stock",
      daysOfInventory: 47,
      lastShipment: "Jan 12, 2025",
      nextShipment: "Jan 25, 2025",
      salesVelocity: "+8%",
      retailPrice: "$649.99",
      priority: "normal",
    },
    {
      distributionCenter: "Ferguson DC - Mocksville, NC",
      productModel: "A.O. Smith Tankless Unit",
      sku: "FRG-WH-TNKLS",
      currentStock: 2340,
      forecastDemand: 8500,
      retailPartner: "General Contractor Accounts",
      region: "Southeast",
      alertType: "Critical Shortage",
      daysOfInventory: 12,
      lastShipment: "Jan 10, 2025",
      nextShipment: "Jan 18, 2025",
      salesVelocity: "+22%",
      retailPrice: "$999.99",
      priority: "critical",
    },
    {
      distributionCenter: "Ferguson DC - Denver, CO",
      productModel: "Trane 15 SEER AC Condensing Unit",
      sku: "FRG-HV-SEER15",
      currentStock: 15680,
      forecastDemand: 12000,
      retailPartner: "HVAC Contractor Accounts",
      region: "Mountain West",
      alertType: "Overstock",
      daysOfInventory: 65,
      lastShipment: "Jan 08, 2025",
      nextShipment: "Feb 01, 2025",
      salesVelocity: "-3%",
      retailPrice: "$1,549.99",
      priority: "low",
    },
    {
      distributionCenter: "Ferguson DC - Phoenix, AZ",
      productModel: "Carrier 3-Ton Heat Pump",
      sku: "FRG-HV-HP3T",
      currentStock: 4560,
      forecastDemand: 9200,
      retailPartner: "HVAC Contractor Accounts",
      region: "Southwest",
      alertType: "Stock Shortage",
      daysOfInventory: 18,
      lastShipment: "Jan 13, 2025",
      nextShipment: "Jan 22, 2025",
      salesVelocity: "+28%",
      retailPrice: "$2,899.00",
      priority: "high",
    },
    {
      distributionCenter: "Ferguson DC - Chicago, IL",
      productModel: "6in Ductile Iron Gate Valve",
      sku: "FRG-WW-GV6",
      currentStock: 3420,
      forecastDemand: 4500,
      retailPartner: "Municipal Water Departments",
      region: "Midwest",
      alertType: "Low Stock",
      daysOfInventory: 28,
      lastShipment: "Jan 11, 2025",
      nextShipment: "Jan 24, 2025",
      salesVelocity: "+12%",
      retailPrice: "$629.99",
      priority: "normal",
    },
    {
      distributionCenter: "Ferguson DC - Atlanta, GA",
      productModel: "1in Copper Press Fitting Kit",
      sku: "FRG-FIT-CU1KIT",
      currentStock: 1890,
      forecastDemand: 2800,
      retailPartner: "Plumbing Contractor Accounts",
      region: "Southeast",
      alertType: "Stock Shortage",
      daysOfInventory: 24,
      lastShipment: "Jan 09, 2025",
      nextShipment: "Jan 19, 2025",
      salesVelocity: "+18%",
      retailPrice: "$349.99",
      priority: "high",
    },
    {
      distributionCenter: "Ferguson DC - Sacramento, CA",
      productModel: "Fire Sprinkler Head - Residential Pendent",
      sku: "FRG-FP-SPRNK12",
      currentStock: 7240,
      forecastDemand: 6800,
      retailPartner: "Fire Protection Contractors",
      region: "West Coast",
      alertType: "Optimal Stock",
      daysOfInventory: 42,
      lastShipment: "Jan 15, 2025",
      nextShipment: "Jan 28, 2025",
      salesVelocity: "+5%",
      retailPrice: "$39.99",
      priority: "normal",
    },
  ]

  return finishedGoodsData.find((item) => slug.includes(item.sku)) || finishedGoodsData[0]
}

export default function ProductDetailPage() {
  const params = useParams()
  const slug = params.slug as string
  const productData = getProductData(slug)

  return <VRProductDashboard productData={productData} />
}
