import type { Facility } from "@/components/map/facility"

export const facilityData: Facility[] = [
  // ── Ferguson Distribution Centers ─────────────────────────────────
  {
    id: "fdc-01",
    name: "Ferguson Master DC - Newport News",
    type: "Distribution",
    status: "Operational",
    lat: 37.0871,
    lng: -76.473,
    country: "USA",
    address: "12500 Jefferson Ave, Newport News, VA 23602",
    capacity: "850,000 sqft",
    efficiency: 96,
    riskScore: 18,
    revenue: "$2.4B",
    leadTime: "1 day",
    onTimeDelivery: 97,
    inventory: 145000,
    connections: 28,
    contactEmail: "newportnews.dc@ferguson.com",
    contactPhone: "+1 757-874-7795",
  },
  {
    id: "fdc-02",
    name: "Ferguson Regional DC - Dallas",
    type: "Distribution",
    status: "Operational",
    lat: 32.7767,
    lng: -96.797,
    country: "USA",
    address: "2800 E Plano Pkwy, Dallas, TX 75074",
    capacity: "425,000 sqft",
    efficiency: 93,
    riskScore: 22,
    revenue: "$1.8B",
    leadTime: "1 day",
    onTimeDelivery: 95,
    inventory: 89000,
    connections: 22,
    contactEmail: "dallas.dc@ferguson.com",
  },
  {
    id: "fdc-03",
    name: "Ferguson Regional DC - Atlanta",
    type: "Distribution",
    status: "Operational",
    lat: 33.749,
    lng: -84.388,
    country: "USA",
    address: "3400 Montreal Industrial Way, Tucker, GA 30084",
    capacity: "380,000 sqft",
    efficiency: 91,
    riskScore: 20,
    revenue: "$1.5B",
    leadTime: "1 day",
    onTimeDelivery: 94,
    inventory: 78000,
    connections: 19,
    contactEmail: "atlanta.dc@ferguson.com",
  },
  {
    id: "fdc-04",
    name: "Ferguson Regional DC - Denver",
    type: "Distribution",
    status: "Operational",
    lat: 39.7392,
    lng: -104.9903,
    country: "USA",
    address: "19500 E 32nd Pkwy, Aurora, CO 80011",
    capacity: "310,000 sqft",
    efficiency: 90,
    riskScore: 15,
    revenue: "$980M",
    leadTime: "2 days",
    onTimeDelivery: 93,
    inventory: 52000,
    connections: 14,
    contactEmail: "denver.dc@ferguson.com",
  },
  {
    id: "fdc-05",
    name: "Ferguson Regional DC - Phoenix",
    type: "Distribution",
    status: "Warning",
    lat: 33.4484,
    lng: -112.074,
    country: "USA",
    address: "4720 W Buckeye Rd, Phoenix, AZ 85043",
    capacity: "295,000 sqft",
    efficiency: 82,
    riskScore: 48,
    revenue: "$870M",
    leadTime: "2 days",
    onTimeDelivery: 87,
    inventory: 41000,
    connections: 12,
    lastIncident: "Extreme heat wave disrupting outbound logistics - 5 days ago",
    contactEmail: "phoenix.dc@ferguson.com",
  },
  {
    id: "fdc-06",
    name: "Ferguson Regional DC - Chicago",
    type: "Distribution",
    status: "Operational",
    lat: 41.8781,
    lng: -87.6298,
    country: "USA",
    address: "1200 N Farnsworth Ave, Aurora, IL 60505",
    capacity: "400,000 sqft",
    efficiency: 92,
    riskScore: 25,
    revenue: "$1.6B",
    leadTime: "1 day",
    onTimeDelivery: 94,
    inventory: 82000,
    connections: 20,
    contactEmail: "chicago.dc@ferguson.com",
  },
  {
    id: "fdc-07",
    name: "Ferguson Regional DC - Sacramento",
    type: "Distribution",
    status: "Operational",
    lat: 38.5816,
    lng: -121.4944,
    country: "USA",
    address: "3720 Channel Dr, West Sacramento, CA 95691",
    capacity: "275,000 sqft",
    efficiency: 89,
    riskScore: 28,
    revenue: "$920M",
    leadTime: "2 days",
    onTimeDelivery: 92,
    inventory: 48000,
    connections: 11,
    contactEmail: "sacramento.dc@ferguson.com",
  },
  {
    id: "fdc-08",
    name: "Ferguson Regional DC - Orlando",
    type: "Distribution",
    status: "Warning",
    lat: 28.5383,
    lng: -81.3792,
    country: "USA",
    address: "7200 Presidents Dr, Orlando, FL 32809",
    capacity: "320,000 sqft",
    efficiency: 84,
    riskScore: 42,
    revenue: "$1.1B",
    leadTime: "1 day",
    onTimeDelivery: 89,
    inventory: 63000,
    connections: 16,
    lastIncident: "Hurricane season inventory pre-staging in progress",
    contactEmail: "orlando.dc@ferguson.com",
  },
  {
    id: "fdc-09",
    name: "Ferguson Regional DC - San Bernardino",
    type: "Distribution",
    status: "Operational",
    lat: 34.1083,
    lng: -117.2898,
    country: "USA",
    address: "1600 W Valley Blvd, Colton, CA 92324",
    capacity: "350,000 sqft",
    efficiency: 91,
    riskScore: 32,
    revenue: "$1.3B",
    leadTime: "1 day",
    onTimeDelivery: 93,
    inventory: 71000,
    connections: 18,
    contactEmail: "sanbernardino.dc@ferguson.com",
  },
  {
    id: "fdc-10",
    name: "Ferguson Regional DC - Indianapolis",
    type: "Distribution",
    status: "Operational",
    lat: 39.7684,
    lng: -86.1581,
    country: "USA",
    address: "5502 W Raymond St, Indianapolis, IN 46241",
    capacity: "290,000 sqft",
    efficiency: 93,
    riskScore: 14,
    revenue: "$1.0B",
    leadTime: "1 day",
    onTimeDelivery: 96,
    inventory: 55000,
    connections: 15,
    contactEmail: "indianapolis.dc@ferguson.com",
  },
  {
    id: "fdc-11",
    name: "Ferguson Regional DC - Charlotte",
    type: "Distribution",
    status: "Operational",
    lat: 35.2271,
    lng: -80.8431,
    country: "USA",
    address: "4801 Brookshire Blvd, Charlotte, NC 28216",
    capacity: "265,000 sqft",
    efficiency: 90,
    riskScore: 19,
    revenue: "$880M",
    leadTime: "1 day",
    onTimeDelivery: 94,
    inventory: 46000,
    connections: 13,
    contactEmail: "charlotte.dc@ferguson.com",
  },
  {
    id: "fdc-12",
    name: "Ferguson Regional DC - Portland",
    type: "Distribution",
    status: "Operational",
    lat: 45.5152,
    lng: -122.6784,
    country: "USA",
    address: "9800 SE McBrod Ave, Portland, OR 97222",
    capacity: "240,000 sqft",
    efficiency: 88,
    riskScore: 16,
    revenue: "$620M",
    leadTime: "2 days",
    onTimeDelivery: 93,
    inventory: 34000,
    connections: 9,
    contactEmail: "portland.dc@ferguson.com",
  },

  // ── US Manufacturing Plants ───────────────────────────────────────
  {
    id: "mfg-koh-wi",
    name: "Kohler Plant - Kohler, WI",
    type: "Plant",
    status: "Operational",
    lat: 43.7394,
    lng: -87.7818,
    country: "USA",
    address: "444 Highland Dr, Kohler, WI 53044",
    capacity: "15,000 units/day",
    efficiency: 94,
    riskScore: 12,
    revenue: "$5.2B",
    leadTime: "3 days",
    onTimeDelivery: 96,
    inventory: 28000,
    connections: 12,
    contactEmail: "supply@kohler.com",
  },
  {
    id: "mfg-koh-sc",
    name: "Kohler Plant - Spartanburg, SC",
    type: "Plant",
    status: "Operational",
    lat: 34.9496,
    lng: -81.932,
    country: "USA",
    address: "Spartanburg Industrial Park, SC 29303",
    capacity: "8,000 units/day",
    efficiency: 91,
    riskScore: 16,
    revenue: "$1.8B",
    leadTime: "3 days",
    onTimeDelivery: 94,
    inventory: 14200,
    connections: 8,
    contactEmail: "spartanburg@kohler.com",
  },
  {
    id: "mfg-moe-nc",
    name: "Moen Plant - New Bern, NC",
    type: "Plant",
    status: "Warning",
    lat: 35.1085,
    lng: -77.0441,
    country: "USA",
    address: "New Bern Industrial Park, NC 28562",
    capacity: "12,000 units/day",
    efficiency: 78,
    riskScore: 52,
    revenue: "$3.8B",
    leadTime: "3 days",
    onTimeDelivery: 85,
    inventory: 18500,
    connections: 10,
    lastIncident: "Hurricane risk zone - elevated seasonal risk",
    contactEmail: "supply@moen.com",
  },
  {
    id: "mfg-del-in",
    name: "Delta Faucet Plant - Greensburg, IN",
    type: "Plant",
    status: "Operational",
    lat: 39.3373,
    lng: -85.4836,
    country: "USA",
    address: "55 E Pearl St, Greensburg, IN 47240",
    capacity: "10,000 units/day",
    efficiency: 92,
    riskScore: 14,
    revenue: "$2.1B",
    leadTime: "2 days",
    onTimeDelivery: 95,
    inventory: 21000,
    connections: 9,
    contactEmail: "supply@deltafaucet.com",
  },
  {
    id: "mfg-del-tn",
    name: "Delta Faucet Plant - Jackson, TN",
    type: "Plant",
    status: "Operational",
    lat: 35.6145,
    lng: -88.8139,
    country: "USA",
    address: "Jackson Industrial Park, TN 38301",
    capacity: "8,500 units/day",
    efficiency: 90,
    riskScore: 18,
    revenue: "$1.4B",
    leadTime: "3 days",
    onTimeDelivery: 93,
    inventory: 16800,
    connections: 7,
    contactEmail: "jackson@deltafaucet.com",
  },
  {
    id: "mfg-aos-tn",
    name: "A.O. Smith Plant - Ashland City, TN",
    type: "Plant",
    status: "Operational",
    lat: 36.2742,
    lng: -87.0644,
    country: "USA",
    address: "Ashland City Industrial Blvd, TN 37015",
    capacity: "6,000 units/day",
    efficiency: 93,
    riskScore: 20,
    revenue: "$3.5B",
    leadTime: "4 days",
    onTimeDelivery: 94,
    inventory: 12400,
    connections: 10,
    contactEmail: "supply@aosmith.com",
  },
  {
    id: "mfg-brw-mi",
    name: "Bradford White Plant - Middleville, MI",
    type: "Plant",
    status: "Operational",
    lat: 42.7131,
    lng: -85.4617,
    country: "USA",
    address: "Middleville Manufacturing Park, MI 49333",
    capacity: "4,500 units/day",
    efficiency: 91,
    riskScore: 15,
    revenue: "$1.2B",
    leadTime: "4 days",
    onTimeDelivery: 95,
    inventory: 8900,
    connections: 6,
    contactEmail: "supply@bradfordwhite.com",
  },
  {
    id: "mfg-chp-nc",
    name: "Charlotte Pipe Plant - Charlotte, NC",
    type: "Plant",
    status: "Operational",
    lat: 35.2271,
    lng: -80.8431,
    country: "USA",
    address: "2109 Randolph Rd, Charlotte, NC 28207",
    capacity: "20,000 ft/day",
    efficiency: 90,
    riskScore: 22,
    revenue: "$1.6B",
    leadTime: "3 days",
    onTimeDelivery: 92,
    inventory: 35000,
    connections: 11,
    contactEmail: "supply@charlottepipe.com",
  },
  {
    id: "mfg-jme-ca",
    name: "JM Eagle Plant - Los Angeles, CA",
    type: "Plant",
    status: "Warning",
    lat: 34.0522,
    lng: -118.2437,
    country: "USA",
    address: "5200 W Century Blvd, Los Angeles, CA 90045",
    capacity: "30,000 ft/day",
    efficiency: 82,
    riskScore: 45,
    revenue: "$2.8B",
    leadTime: "3 days",
    onTimeDelivery: 88,
    inventory: 42000,
    connections: 8,
    lastIncident: "Seismic zone - earthquake preparedness drill completed",
    contactEmail: "supply@jmeagle.com",
  },
  {
    id: "mfg-jme-tx",
    name: "JM Eagle Plant - Houston, TX",
    type: "Plant",
    status: "Operational",
    lat: 29.7604,
    lng: -95.3698,
    country: "USA",
    address: "Houston Ship Channel Industrial, TX 77049",
    capacity: "25,000 ft/day",
    efficiency: 88,
    riskScore: 38,
    revenue: "$1.9B",
    leadTime: "3 days",
    onTimeDelivery: 90,
    inventory: 38000,
    connections: 7,
    contactEmail: "houston@jmeagle.com",
  },
  {
    id: "mfg-mwp-al",
    name: "Mueller Water Plant - Albertville, AL",
    type: "Plant",
    status: "Operational",
    lat: 34.2676,
    lng: -86.2086,
    country: "USA",
    address: "Albertville Industrial Park, AL 35950",
    capacity: "3,000 units/day",
    efficiency: 89,
    riskScore: 26,
    revenue: "$1.8B",
    leadTime: "5 days",
    onTimeDelivery: 91,
    inventory: 7800,
    connections: 8,
    contactEmail: "supply@muellerwp.com",
  },
  {
    id: "mfg-rhe-al",
    name: "Rheem Plant - Montgomery, AL",
    type: "Plant",
    status: "Warning",
    lat: 32.3668,
    lng: -86.3,
    country: "USA",
    address: "Montgomery Industrial Park, AL 36109",
    capacity: "5,500 units/day",
    efficiency: 79,
    riskScore: 55,
    revenue: "$5.5B",
    leadTime: "4 days",
    onTimeDelivery: 84,
    inventory: 9200,
    connections: 10,
    lastIncident: "Tornado warning zone - elevated seasonal risk",
    contactEmail: "supply@rheem.com",
  },
  {
    id: "mfg-tra-sc",
    name: "Trane Plant - Columbia, SC",
    type: "Plant",
    status: "Operational",
    lat: 34.0007,
    lng: -81.0348,
    country: "USA",
    address: "Columbia Manufacturing Facility, SC 29201",
    capacity: "4,000 units/day",
    efficiency: 92,
    riskScore: 17,
    revenue: "$4.2B",
    leadTime: "5 days",
    onTimeDelivery: 93,
    inventory: 6500,
    connections: 8,
    contactEmail: "supply@trane.com",
  },
  {
    id: "mfg-car-in",
    name: "Carrier Plant - Indianapolis, IN",
    type: "Plant",
    status: "Operational",
    lat: 39.7684,
    lng: -86.1581,
    country: "USA",
    address: "Indianapolis Manufacturing, IN 46241",
    capacity: "3,500 units/day",
    efficiency: 91,
    riskScore: 19,
    revenue: "$3.8B",
    leadTime: "5 days",
    onTimeDelivery: 92,
    inventory: 5800,
    connections: 7,
    contactEmail: "supply@carrier.com",
  },
  {
    id: "mfg-len-ia",
    name: "Lennox Plant - Marshalltown, IA",
    type: "Plant",
    status: "Operational",
    lat: 42.0494,
    lng: -92.908,
    country: "USA",
    address: "Marshalltown Manufacturing, IA 50158",
    capacity: "3,200 units/day",
    efficiency: 90,
    riskScore: 21,
    revenue: "$3.1B",
    leadTime: "5 days",
    onTimeDelivery: 92,
    inventory: 5200,
    connections: 6,
    contactEmail: "supply@lennox.com",
  },
  {
    id: "mfg-gen-wi",
    name: "Generac Plant - Waukesha, WI",
    type: "Plant",
    status: "Operational",
    lat: 43.0117,
    lng: -88.2315,
    country: "USA",
    address: "S45 W29290 Hwy 59, Waukesha, WI 53189",
    capacity: "2,000 units/day",
    efficiency: 88,
    riskScore: 23,
    revenue: "$2.4B",
    leadTime: "7 days",
    onTimeDelivery: 90,
    inventory: 4100,
    connections: 5,
    contactEmail: "supply@generac.com",
  },
  {
    id: "mfg-ins-wi",
    name: "InSinkErator Plant - Racine, WI",
    type: "Plant",
    status: "Operational",
    lat: 42.7261,
    lng: -87.7829,
    country: "USA",
    address: "4700 21st St, Racine, WI 53406",
    capacity: "8,000 units/day",
    efficiency: 93,
    riskScore: 10,
    revenue: "$1.1B",
    leadTime: "3 days",
    onTimeDelivery: 96,
    inventory: 19000,
    connections: 9,
    contactEmail: "supply@insinkerator.com",
  },
  {
    id: "mfg-rin-ga",
    name: "Rinnai Plant - Griffin, GA",
    type: "Plant",
    status: "Operational",
    lat: 33.2468,
    lng: -84.2641,
    country: "USA",
    address: "Griffin Industrial Park, GA 30223",
    capacity: "2,500 units/day",
    efficiency: 91,
    riskScore: 18,
    revenue: "$980M",
    leadTime: "4 days",
    onTimeDelivery: 94,
    inventory: 5400,
    connections: 6,
    contactEmail: "supply@rinnai.us",
  },

  // ── Supplier Headquarters ─────────────────────────────────────────
  {
    id: "sup-koh",
    name: "Kohler Co. HQ",
    type: "Supplier",
    status: "Operational",
    lat: 43.7394,
    lng: -87.7818,
    country: "USA",
    address: "444 Highland Dr, Kohler, WI 53044",
    capacity: "Global supplier",
    efficiency: 95,
    riskScore: 12,
    revenue: "$8.0B",
    leadTime: "3 days",
    onTimeDelivery: 96,
    inventory: 42000,
    connections: 14,
    contactEmail: "b2b@kohler.com",
    contactPhone: "+1 920-457-4441",
  },
  {
    id: "sup-moe",
    name: "Moen Inc. HQ",
    type: "Supplier",
    status: "Operational",
    lat: 41.4156,
    lng: -81.9235,
    country: "USA",
    address: "25300 Al Moen Dr, North Olmsted, OH 44070",
    capacity: "Global supplier",
    efficiency: 92,
    riskScore: 22,
    revenue: "$3.8B",
    leadTime: "3 days",
    onTimeDelivery: 93,
    inventory: 35000,
    connections: 12,
    contactEmail: "b2b@moen.com",
  },
  {
    id: "sup-ams",
    name: "American Standard (LIXIL) HQ",
    type: "Supplier",
    status: "Operational",
    lat: 40.5492,
    lng: -74.4593,
    country: "USA",
    address: "1 Centennial Ave, Piscataway, NJ 08854",
    capacity: "Global supplier",
    efficiency: 90,
    riskScore: 24,
    revenue: "$3.2B",
    leadTime: "4 days",
    onTimeDelivery: 92,
    inventory: 28000,
    connections: 10,
    contactEmail: "b2b@americanstandard.com",
  },
  {
    id: "sup-rhe",
    name: "Rheem Manufacturing HQ",
    type: "Supplier",
    status: "Operational",
    lat: 33.749,
    lng: -84.388,
    country: "USA",
    address: "1100 Abernathy Rd NE, Atlanta, GA 30328",
    capacity: "Global supplier",
    efficiency: 88,
    riskScore: 30,
    revenue: "$5.5B",
    leadTime: "4 days",
    onTimeDelivery: 91,
    inventory: 22000,
    connections: 14,
    contactEmail: "b2b@rheem.com",
  },
  {
    id: "sup-tra",
    name: "Trane Technologies HQ",
    type: "Supplier",
    status: "Operational",
    lat: 35.4993,
    lng: -80.8487,
    country: "USA",
    address: "800 Beaty St, Davidson, NC 28036",
    capacity: "Global supplier",
    efficiency: 93,
    riskScore: 15,
    revenue: "$16.0B",
    leadTime: "5 days",
    onTimeDelivery: 94,
    inventory: 18000,
    connections: 10,
    contactEmail: "b2b@trane.com",
  },
  {
    id: "sup-car",
    name: "Carrier Global HQ",
    type: "Supplier",
    status: "Operational",
    lat: 26.8234,
    lng: -80.1387,
    country: "USA",
    address: "13995 Pasteur Blvd, Palm Beach Gardens, FL 33418",
    capacity: "Global supplier",
    efficiency: 91,
    riskScore: 18,
    revenue: "$20.4B",
    leadTime: "5 days",
    onTimeDelivery: 93,
    inventory: 15000,
    connections: 9,
    contactEmail: "b2b@carrier.com",
  },
  {
    id: "sup-len",
    name: "Lennox International HQ",
    type: "Supplier",
    status: "Operational",
    lat: 32.9483,
    lng: -96.7299,
    country: "USA",
    address: "2140 Lake Park Blvd, Richardson, TX 75080",
    capacity: "Global supplier",
    efficiency: 90,
    riskScore: 20,
    revenue: "$4.7B",
    leadTime: "5 days",
    onTimeDelivery: 92,
    inventory: 12000,
    connections: 8,
    contactEmail: "b2b@lennox.com",
  },
  {
    id: "sup-aos",
    name: "A.O. Smith Corporation HQ",
    type: "Supplier",
    status: "Operational",
    lat: 43.0389,
    lng: -87.9065,
    country: "USA",
    address: "11270 W Park Pl, Milwaukee, WI 53224",
    capacity: "Global supplier",
    efficiency: 92,
    riskScore: 16,
    revenue: "$3.5B",
    leadTime: "4 days",
    onTimeDelivery: 95,
    inventory: 16000,
    connections: 10,
    contactEmail: "b2b@aosmith.com",
  },
  {
    id: "sup-brw",
    name: "Bradford White HQ",
    type: "Supplier",
    status: "Operational",
    lat: 40.1543,
    lng: -75.2215,
    country: "USA",
    address: "725 Talamore Dr, Ambler, PA 19002",
    capacity: "Wholesale exclusive",
    efficiency: 91,
    riskScore: 28,
    revenue: "$1.2B",
    leadTime: "4 days",
    onTimeDelivery: 93,
    inventory: 9500,
    connections: 7,
    contactEmail: "b2b@bradfordwhite.com",
  },
  {
    id: "sup-chp",
    name: "Charlotte Pipe and Foundry HQ",
    type: "Supplier",
    status: "Operational",
    lat: 35.2271,
    lng: -80.8431,
    country: "USA",
    address: "2109 Randolph Rd, Charlotte, NC 28207",
    capacity: "National supplier",
    efficiency: 89,
    riskScore: 24,
    revenue: "$1.6B",
    leadTime: "3 days",
    onTimeDelivery: 91,
    inventory: 38000,
    connections: 11,
    contactEmail: "b2b@charlottepipe.com",
  },
  {
    id: "sup-jme",
    name: "JM Eagle HQ",
    type: "Supplier",
    status: "Operational",
    lat: 34.0522,
    lng: -118.2437,
    country: "USA",
    address: "5200 W Century Blvd, Los Angeles, CA 90045",
    capacity: "World largest PVC pipe mfr",
    efficiency: 87,
    riskScore: 32,
    revenue: "$2.8B",
    leadTime: "3 days",
    onTimeDelivery: 89,
    inventory: 52000,
    connections: 9,
    contactEmail: "b2b@jmeagle.com",
  },
  {
    id: "sup-mwp",
    name: "Mueller Water Products HQ",
    type: "Supplier",
    status: "Operational",
    lat: 33.749,
    lng: -84.388,
    country: "USA",
    address: "1200 Abernathy Rd NE, Atlanta, GA 30328",
    capacity: "National supplier",
    efficiency: 88,
    riskScore: 26,
    revenue: "$1.3B",
    leadTime: "5 days",
    onTimeDelivery: 90,
    inventory: 11000,
    connections: 9,
    contactEmail: "b2b@muellerwp.com",
  },
  {
    id: "sup-wat",
    name: "Watts Water Technologies HQ",
    type: "Supplier",
    status: "Operational",
    lat: 42.6987,
    lng: -71.1323,
    country: "USA",
    address: "815 Chestnut St, North Andover, MA 01845",
    capacity: "Global supplier",
    efficiency: 91,
    riskScore: 19,
    revenue: "$2.0B",
    leadTime: "4 days",
    onTimeDelivery: 93,
    inventory: 8500,
    connections: 7,
    contactEmail: "b2b@wattswater.com",
  },
  {
    id: "sup-upo",
    name: "Uponor HQ",
    type: "Supplier",
    status: "Operational",
    lat: 44.7319,
    lng: -93.2177,
    country: "USA",
    address: "5925 148th St W, Apple Valley, MN 55124",
    capacity: "PEX tubing leader",
    efficiency: 92,
    riskScore: 14,
    revenue: "$1.4B",
    leadTime: "3 days",
    onTimeDelivery: 95,
    inventory: 24000,
    connections: 8,
    contactEmail: "b2b@uponor.com",
  },
  {
    id: "sup-vie",
    name: "Viega LLC HQ",
    type: "Supplier",
    status: "Operational",
    lat: 37.6872,
    lng: -97.3301,
    country: "USA",
    address: "585 Interlocken Blvd, Wichita, KS 67226",
    capacity: "Press-fit specialist",
    efficiency: 93,
    riskScore: 12,
    revenue: "$1.1B",
    leadTime: "3 days",
    onTimeDelivery: 96,
    inventory: 18000,
    connections: 7,
    contactEmail: "b2b@viega.us",
  },
  {
    id: "sup-hon",
    name: "Resideo (Honeywell Home) HQ",
    type: "Supplier",
    status: "Operational",
    lat: 33.4942,
    lng: -111.9261,
    country: "USA",
    address: "16100 N 71st St, Scottsdale, AZ 85254",
    capacity: "Smart home controls",
    efficiency: 89,
    riskScore: 20,
    revenue: "$5.4B",
    leadTime: "3 days",
    onTimeDelivery: 92,
    inventory: 14000,
    connections: 6,
    contactEmail: "b2b@resideo.com",
  },
  {
    id: "sup-gen",
    name: "Generac Power Systems HQ",
    type: "Supplier",
    status: "Operational",
    lat: 43.0117,
    lng: -88.2315,
    country: "USA",
    address: "S45 W29290 Hwy 59, Waukesha, WI 53189",
    capacity: "Generator leader",
    efficiency: 88,
    riskScore: 23,
    revenue: "$4.0B",
    leadTime: "7 days",
    onTimeDelivery: 90,
    inventory: 6200,
    connections: 5,
    contactEmail: "b2b@generac.com",
  },

  // ── Overseas Manufacturing ────────────────────────────────────────
  {
    id: "mfg-koh-cn",
    name: "Kohler Plant - Foshan, China",
    type: "Plant",
    status: "Critical",
    lat: 23.0218,
    lng: 113.1219,
    country: "China",
    address: "Foshan Hi-Tech Industrial Zone, Guangdong, China",
    capacity: "20,000 units/day",
    efficiency: 88,
    riskScore: 78,
    revenue: "$1.2B",
    leadTime: "45 days",
    onTimeDelivery: 82,
    inventory: 32000,
    connections: 4,
    lastIncident: "25% Section 301 tariff active - COGS impact $45M/yr",
    contactEmail: "foshan@kohler.com",
  },
  {
    id: "mfg-moe-cn",
    name: "Moen Plant - Jiangmen, China",
    type: "Plant",
    status: "Critical",
    lat: 22.579,
    lng: 113.0784,
    country: "China",
    address: "Jiangmen Industrial Park, Guangdong, China",
    capacity: "18,000 units/day",
    efficiency: 86,
    riskScore: 76,
    revenue: "$980M",
    leadTime: "42 days",
    onTimeDelivery: 80,
    inventory: 28000,
    connections: 3,
    lastIncident: "Section 301 tariff + Guangdong typhoon season risk",
    contactEmail: "jiangmen@moen.com",
  },
  {
    id: "mfg-del-cn",
    name: "Delta Faucet Plant - Zhuhai, China",
    type: "Plant",
    status: "Critical",
    lat: 22.271,
    lng: 113.5767,
    country: "China",
    address: "Zhuhai Free Trade Zone, Guangdong, China",
    capacity: "15,000 units/day",
    efficiency: 85,
    riskScore: 74,
    revenue: "$720M",
    leadTime: "45 days",
    onTimeDelivery: 81,
    inventory: 22000,
    connections: 3,
    lastIncident: "25% tariff active - nearshoring evaluation underway",
    contactEmail: "zhuhai@deltafaucet.com",
  },
  {
    id: "mfg-ams-mx",
    name: "American Standard Plant - Monterrey, MX",
    type: "Plant",
    status: "Operational",
    lat: 25.6866,
    lng: -100.3161,
    country: "Mexico",
    address: "Parque Industrial Monterrey, Nuevo Leon, Mexico",
    capacity: "10,000 units/day",
    efficiency: 87,
    riskScore: 35,
    revenue: "$1.4B",
    leadTime: "7 days",
    onTimeDelivery: 90,
    inventory: 18000,
    connections: 6,
    contactEmail: "monterrey@americanstandard.com",
  },
  {
    id: "mfg-rhe-mx",
    name: "Rheem Plant - Monterrey, MX",
    type: "Plant",
    status: "Operational",
    lat: 25.6866,
    lng: -100.3161,
    country: "Mexico",
    address: "Parque Industrial Santa Catarina, Nuevo Leon, Mexico",
    capacity: "4,000 units/day",
    efficiency: 86,
    riskScore: 33,
    revenue: "$880M",
    leadTime: "7 days",
    onTimeDelivery: 89,
    inventory: 7200,
    connections: 5,
    contactEmail: "monterrey@rheem.com",
  },
  {
    id: "mfg-tot-jp",
    name: "TOTO Plant - Kitakyushu, Japan",
    type: "Plant",
    status: "Operational",
    lat: 33.8835,
    lng: 130.8753,
    country: "Japan",
    address: "1-1 Nakashima, Kokurakita-ku, Kitakyushu, Japan",
    capacity: "12,000 units/day",
    efficiency: 97,
    riskScore: 22,
    revenue: "$5.6B",
    leadTime: "35 days",
    onTimeDelivery: 97,
    inventory: 15000,
    connections: 4,
    contactEmail: "export@toto.co.jp",
  },
  {
    id: "mfg-gro-de",
    name: "Grohe Plant - Hemer, Germany",
    type: "Plant",
    status: "Operational",
    lat: 51.3867,
    lng: 7.7706,
    country: "Germany",
    address: "Industriepark Hemer, North Rhine-Westphalia, Germany",
    capacity: "8,000 units/day",
    efficiency: 95,
    riskScore: 16,
    revenue: "$2.4B",
    leadTime: "28 days",
    onTimeDelivery: 96,
    inventory: 11000,
    connections: 4,
    contactEmail: "export@grohe.com",
  },
  {
    id: "mfg-gro-th",
    name: "Grohe Plant - Klaeng, Thailand",
    type: "Plant",
    status: "Warning",
    lat: 12.7783,
    lng: 101.6489,
    country: "Thailand",
    address: "Eastern Seaboard Industrial Estate, Rayong, Thailand",
    capacity: "10,000 units/day",
    efficiency: 84,
    riskScore: 44,
    revenue: "$680M",
    leadTime: "40 days",
    onTimeDelivery: 86,
    inventory: 14000,
    connections: 3,
    lastIncident: "Monsoon flooding risk - seasonal monitoring active",
    contactEmail: "klaeng@grohe.com",
  },
  {
    id: "mfg-nav-kr",
    name: "Navien Plant - Sejong, South Korea",
    type: "Plant",
    status: "Operational",
    lat: 36.48,
    lng: 127.0,
    country: "South Korea",
    address: "Sejong Special Autonomous City, South Korea",
    capacity: "6,000 units/day",
    efficiency: 94,
    riskScore: 18,
    revenue: "$1.8B",
    leadTime: "38 days",
    onTimeDelivery: 95,
    inventory: 8400,
    connections: 4,
    contactEmail: "export@navien.com",
  },
  {
    id: "mfg-nor-jp",
    name: "Noritz Plant - Akashi, Japan",
    type: "Plant",
    status: "Operational",
    lat: 34.6432,
    lng: 134.9973,
    country: "Japan",
    address: "Akashi Industrial Zone, Hyogo, Japan",
    capacity: "4,500 units/day",
    efficiency: 96,
    riskScore: 15,
    revenue: "$1.2B",
    leadTime: "35 days",
    onTimeDelivery: 97,
    inventory: 6200,
    connections: 3,
    contactEmail: "export@noritz.co.jp",
  },
  {
    id: "mfg-upo-fi",
    name: "Uponor Plant - Nastola, Finland",
    type: "Plant",
    status: "Operational",
    lat: 60.949,
    lng: 25.9323,
    country: "Finland",
    address: "Nastola Industrial Park, Paijat-Hame, Finland",
    capacity: "50,000 ft/day",
    efficiency: 94,
    riskScore: 10,
    revenue: "$420M",
    leadTime: "30 days",
    onTimeDelivery: 96,
    inventory: 28000,
    connections: 3,
    contactEmail: "export@uponor.com",
  },
  {
    id: "mfg-vie-de",
    name: "Viega Plant - Attendorn, Germany",
    type: "Plant",
    status: "Operational",
    lat: 51.1267,
    lng: 7.9033,
    country: "Germany",
    address: "Attendorn Industrial Park, North Rhine-Westphalia, Germany",
    capacity: "25,000 units/day",
    efficiency: 95,
    riskScore: 11,
    revenue: "$1.1B",
    leadTime: "28 days",
    onTimeDelivery: 97,
    inventory: 32000,
    connections: 4,
    contactEmail: "export@viega.de",
  },
]
