import type { NetworkModel, OptimizationScenario } from "./types"

export const initialNetworkModel: NetworkModel = {
  costBreakdown: {
    totalCost: 146100,
    idFixedCost: 900,
    idTransport: 9800,
    idHandling: 6400,
    podTransport: 126000,
    podDeliveryProcessing: 3000,
  },
  intermediateDepots: [
    {
      id: "Ferguson Cross-Dock Southeast",
      varCost: 1.35,
      fixedCost: 1100,
      isOpen: false,
      flowFromCDC: 0,
      transportCost: 2.4,
    },
    {
      id: "Ferguson Cross-Dock West",
      varCost: 1.6,
      fixedCost: 900,
      isOpen: true,
      flowFromCDC: 4000,
      transportCost: 2.45,
    },
  ],
  channelFlows: [
    {
      channelName: "Ferguson Branch (Walk-in)",
      fromCDC: 27750,
      fromID1: 0,
      fromID2: 0,
      delivered: 27750,
      demanded: 27750,
      varCost: 0.5,
    },
    {
      channelName: "Contractor Direct (Job Site)",
      fromCDC: 92250,
      fromID1: 0,
      fromID2: 0,
      delivered: 92250,
      demanded: 92250,
      varCost: 0,
    },
    {
      channelName: "Ferguson.com (Online)",
      fromCDC: 0,
      fromID1: 0,
      fromID2: 6250,
      delivered: 6250,
      demanded: 6250,
      varCost: 0.75,
    },
    {
      channelName: "Will-Call / Delivery",
      fromCDC: 0,
      fromID1: 0,
      fromID2: 18750,
      delivered: 18750,
      demanded: 18750,
      varCost: 0,
    },
  ],
  totalDemand: 145000,
  idsToOpen: {
    number: 1,
    min: 0,
    max: 2,
  },
  transportCosts: [
    {
      from: "Ferguson Master DC",
      convStore: 6.6,
      retailStore: 5.85,
      aps: 6.25,
      home: 8.15,
    },
    {
      from: "Ferguson Cross-Dock Southeast",
      convStore: 2.2,
      retailStore: 2.1,
      aps: 9999.0,
      home: 9999.0,
    },
    {
      from: "Ferguson Cross-Dock West",
      convStore: 9999.0,
      retailStore: 9999.0,
      aps: 1.05,
      home: 3.4,
    },
  ],
  constraints: [
    {
      name: "Ferguson Cross-Dock Southeast Capacity",
      value: 0,
      operator: "<=",
      limit: 20000,
    },
    {
      name: "Ferguson Cross-Dock West Capacity",
      value: 19500,
      operator: "<=",
      limit: 5000,
    },
    {
      name: "Ferguson Cross-Dock Southeast Balance",
      value: 0,
      operator: "=",
      limit: 0,
    },
    {
      name: "Ferguson Cross-Dock West Balance",
      value: 0,
      operator: "=",
      limit: 0,
    },
  ],
}

export const initialScenarios: OptimizationScenario[] = [
  {
    id: "scenario-1",
    name: "Base Case",
    description: "Current network configuration with existing delivery options",
    createdAt: new Date(2025, 4, 20),
    totalCost: 146100,
    model: initialNetworkModel,
  },
  {
    id: "scenario-2",
    name: "Expanded Ferguson.com (Online)",
    description: "Increased use of Ferguson.com online ordering channel",
    createdAt: new Date(2025, 4, 21),
    totalCost: 142500,
    model: {
      ...initialNetworkModel,
      costBreakdown: {
        ...initialNetworkModel.costBreakdown,
        totalCost: 142500,
        podTransport: 122400,
      },
      channelFlows: [
        {
          channelName: "Ferguson Branch (Walk-in)",
          fromCDC: 27750,
          fromID1: 0,
          fromID2: 0,
          delivered: 27750,
          demanded: 27750,
          varCost: 0.5,
        },
        {
          channelName: "Contractor Direct (Job Site)",
          fromCDC: 92250,
          fromID1: 0,
          fromID2: 0,
          delivered: 92250,
          demanded: 92250,
          varCost: 0,
        },
        {
          channelName: "Ferguson.com (Online)",
          fromCDC: 0,
          fromID1: 0,
          fromID2: 12500,
          delivered: 12500,
          demanded: 12500,
          varCost: 0.75,
        },
        {
          channelName: "Will-Call / Delivery",
          fromCDC: 0,
          fromID1: 0,
          fromID2: 12500,
          delivered: 12500,
          demanded: 12500,
          varCost: 0,
        },
      ],
    },
  },
  {
    id: "scenario-3",
    name: "Both Cross-Docks Open",
    description: "Operating both Ferguson cross-dock facilities",
    createdAt: new Date(2025, 4, 22),
    totalCost: 144800,
    model: {
      ...initialNetworkModel,
      costBreakdown: {
        ...initialNetworkModel.costBreakdown,
        totalCost: 144800,
        idFixedCost: 2000,
        idTransport: 8600,
      },
      intermediateDepots: [
        {
          id: "Ferguson Cross-Dock Southeast",
          varCost: 1.35,
          fixedCost: 1100,
          isOpen: true,
          flowFromCDC: 2000,
          transportCost: 2.4,
        },
        {
          id: "Ferguson Cross-Dock West",
          varCost: 1.6,
          fixedCost: 900,
          isOpen: true,
          flowFromCDC: 2000,
          transportCost: 2.45,
        },
      ],
    },
  },
]
