"use client"

import { useState } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Download, FileSpreadsheet, FileText, File } from "lucide-react"
import * as XLSX from "xlsx"

interface ExportDialogProps {
  data: any[]
  filteredData: any[]
  searchTerm: string
}

export default function EnhancedExportDialog({ data, filteredData, searchTerm }: ExportDialogProps) {
  const [exportFormat, setExportFormat] = useState("xlsx")
  const [includeMetadata, setIncludeMetadata] = useState(true)
  const [selectedColumns, setSelectedColumns] = useState<string[]>([
    "storageType",
    "pickType",
    "routing",
    "instruction",
    "country",
    "resource",
    "process",
    "region",
    "identifier",
    "unit",
    "cost",
    "resource2",
    "unitCost",
    "cost2",
    "totalCost",
    "cost3",
    "cost4",
    "totalCost2",
    "value",
  ])

  const columnLabels = {
    storageType: "Storage Type",
    pickType: "Pick Type",
    routing: "Routing",
    instruction: "Instruction",
    country: "Country",
    resource: "Resource",
    process: "Process",
    region: "Region",
    identifier: "Identifier",
    unit: "Unit",
    cost: "Cost",
    resource2: "Resource 2",
    unitCost: "Unit Cost",
    cost2: "Cost 2",
    totalCost: "Total Cost",
    cost3: "Cost 3",
    cost4: "Cost 4",
    totalCost2: "Total Cost 2",
    value: "Value",
  }

  const handleColumnToggle = (column: string) => {
    setSelectedColumns((prev) => (prev.includes(column) ? prev.filter((col) => col !== column) : [...prev, column]))
  }

  const handleExport = () => {
    // Prepare data with selected columns only
    const exportData = filteredData.map((row, index) => {
      const filteredRow: any = { "Row #": index + 1 }
      selectedColumns.forEach((col) => {
        filteredRow[columnLabels[col as keyof typeof columnLabels]] = row[col]
      })
      return filteredRow
    })

    if (exportFormat === "xlsx") {
      exportToExcel(exportData)
    } else if (exportFormat === "csv") {
      exportToCSV(exportData)
    } else if (exportFormat === "json") {
      exportToJSON(exportData)
    }
  }

  const exportToExcel = (exportData: any[]) => {
    const wb = XLSX.utils.book_new()
    const ws = XLSX.utils.json_to_sheet(exportData)

    // Set column widths
    const colWidths = Array(selectedColumns.length + 1).fill({ wch: 12 })
    ws["!cols"] = colWidths

    // Style the header row
    const headerStyle = {
      font: { bold: true, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "4472C4" } },
      alignment: { horizontal: "center", vertical: "center" },
    }

    // Apply header styling
    const range = XLSX.utils.decode_range(ws["!ref"] || "A1")
    for (let col = range.s.c; col <= range.e.c; col++) {
      const cellAddress = XLSX.utils.encode_cell({ r: 0, c: col })
      if (!ws[cellAddress]) continue
      ws[cellAddress].s = headerStyle
    }

    XLSX.utils.book_append_sheet(wb, ws, "Warehouse Data")

    if (includeMetadata) {
      const metadataSheet = XLSX.utils.json_to_sheet([
        { Property: "Export Date", Value: new Date().toLocaleString() },
        { Property: "Total Records", Value: filteredData.length },
        { Property: "Search Filter", Value: searchTerm || "None" },
        { Property: "Selected Columns", Value: selectedColumns.length },
        { Property: "Export Format", Value: exportFormat.toUpperCase() },
        { Property: "Generated By", Value: "Warehouse Costing & Analytics Platform" },
      ])
      XLSX.utils.book_append_sheet(wb, metadataSheet, "Export Info")

      // Add summary statistics
      const summaryData = [
        { Metric: "Total Unique Countries", Value: [...new Set(filteredData.map((row) => row.country))].length },
        { Metric: "Total Unique Processes", Value: [...new Set(filteredData.map((row) => row.process))].length },
        { Metric: "Total Unique Resources", Value: [...new Set(filteredData.map((row) => row.resource))].length },
        {
          Metric: "Average Cost",
          Value: (
            filteredData.reduce((sum, row) => sum + Number.parseFloat(row.cost || 0), 0) / filteredData.length
          ).toFixed(2),
        },
      ]
      const summarySheet = XLSX.utils.json_to_sheet(summaryData)
      XLSX.utils.book_append_sheet(wb, summarySheet, "Summary")
    }

    const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-")
    const filename = `warehouse-operations-${timestamp}.xlsx`

    // Use browser-compatible write method
    const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" })
    const blob = new Blob([wbout], { type: "application/octet-stream" })

    // Create download link
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", filename)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const exportToCSV = (exportData: any[]) => {
    const ws = XLSX.utils.json_to_sheet(exportData)
    const csv = XLSX.utils.sheet_to_csv(ws)

    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" })
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", `warehouse-operations-${new Date().toISOString().slice(0, 10)}.csv`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const exportToJSON = (exportData: any[]) => {
    const jsonData = {
      exportInfo: {
        exportDate: new Date().toISOString(),
        totalRecords: filteredData.length,
        searchFilter: searchTerm || "None",
        selectedColumns: selectedColumns.length,
      },
      data: exportData,
    }

    const blob = new Blob([JSON.stringify(jsonData, null, 2)], { type: "application/json" })
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", `warehouse-operations-${new Date().toISOString().slice(0, 10)}.json`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          className="flex items-center gap-2 text-purple-700 hover:text-purple-800 hover:bg-purple-100 bg-transparent"
        >
          <div className="bg-purple-600 rounded-full w-6 h-6 flex items-center justify-center">
            <Download className="h-3 w-3 text-white" />
          </div>
          <span className="text-xs">Advanced Export</span>
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Export Warehouse Data</DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* Export Format Selection */}
          <div className="space-y-2">
            <Label>Export Format</Label>
            <Select value={exportFormat} onValueChange={setExportFormat}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="xlsx">
                  <div className="flex items-center gap-2">
                    <FileSpreadsheet className="h-4 w-4 text-green-600" />
                    Excel (.xlsx)
                  </div>
                </SelectItem>
                <SelectItem value="csv">
                  <div className="flex items-center gap-2">
                    <FileText className="h-4 w-4 text-blue-600" />
                    CSV (.csv)
                  </div>
                </SelectItem>
                <SelectItem value="json">
                  <div className="flex items-center gap-2">
                    <File className="h-4 w-4 text-orange-600" />
                    JSON (.json)
                  </div>
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Column Selection */}
          <div className="space-y-2">
            <Label>Select Columns to Export</Label>
            <div className="grid grid-cols-2 gap-2 max-h-48 overflow-y-auto border rounded p-3">
              {Object.entries(columnLabels).map(([key, label]) => (
                <div key={key} className="flex items-center space-x-2">
                  <Checkbox
                    id={key}
                    checked={selectedColumns.includes(key)}
                    onCheckedChange={() => handleColumnToggle(key)}
                  />
                  <Label htmlFor={key} className="text-sm">
                    {label}
                  </Label>
                </div>
              ))}
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => setSelectedColumns(Object.keys(columnLabels))}>
                Select All
              </Button>
              <Button variant="outline" size="sm" onClick={() => setSelectedColumns([])}>
                Clear All
              </Button>
            </div>
          </div>

          {/* Options */}
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <Checkbox id="metadata" checked={includeMetadata} onCheckedChange={(checked) => setIncludeMetadata(checked === true)} />
              <Label htmlFor="metadata">Include metadata and summary sheets (Excel only)</Label>
            </div>
          </div>

          {/* Export Info */}
          <div className="bg-blue-50 p-3 rounded-lg">
            <h4 className="font-semibold text-blue-800 mb-2">Export Summary</h4>
            <div className="text-sm text-blue-700 space-y-1">
              <p>
                Records to export: <strong>{filteredData.length}</strong>
              </p>
              <p>
                Columns selected: <strong>{selectedColumns.length}</strong>
              </p>
              <p>
                Format: <strong>{exportFormat.toUpperCase()}</strong>
              </p>
              {searchTerm && (
                <p>
                  Filter applied: <strong>"{searchTerm}"</strong>
                </p>
              )}
            </div>
          </div>

          {/* Export Button */}
          <Button onClick={handleExport} className="w-full" disabled={selectedColumns.length === 0}>
            <Download className="mr-2 h-4 w-4" />
            Export Data
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
