"use client"

import { useState } from "react"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle } from "@/components/ui/card"
import { Search, Download, RefreshCw } from "lucide-react"
import * as XLSX from "xlsx"
import EnhancedExportDialog from "@/components/others/enhanced-export-dialog"

export default function WarehouseDataTable() {
  const [searchTerm, setSearchTerm] = useState("")

  // Filter data based on search term
  const filteredData = warehouseData.filter((row) => {
    return Object.values(row).some(
      (value) => value && value.toString().toLowerCase().includes(searchTerm.toLowerCase()),
    )
  })

  const handleExportToXLS = () => {
    // Prepare data for export
    const exportData = filteredData.map((row, index) => ({
      "Row #": index + 1,
      "Storage Type": row.storageType,
      "Pick Type": row.pickType,
      Routing: row.routing,
      Instruction: row.instruction,
      Country: row.country,
      Resource: row.resource,
      Process: row.process,
      Region: row.region,
      Identifier: row.identifier,
      Unit: row.unit,
      Cost: row.cost,
      "Resource 2": row.resource2,
      "Unit Cost": row.unitCost,
      "Cost 2": row.cost2,
      "Total Cost": row.totalCost,
      "Cost 3": row.cost3,
      "Cost 4": row.cost4,
      "Total Cost 2": row.totalCost2,
      Value: row.value,
    }))

    // Create workbook and worksheet
    const wb = XLSX.utils.book_new()
    const ws = XLSX.utils.json_to_sheet(exportData)

    // Set column widths
    const colWidths = [
      { wch: 8 }, // Row #
      { wch: 12 }, // Storage Type
      { wch: 10 }, // Pick Type
      { wch: 8 }, // Routing
      { wch: 12 }, // Instruction
      { wch: 12 }, // Country
      { wch: 12 }, // Resource
      { wch: 15 }, // Process
      { wch: 12 }, // Region
      { wch: 10 }, // Identifier
      { wch: 8 }, // Unit
      { wch: 10 }, // Cost
      { wch: 12 }, // Resource 2
      { wch: 12 }, // Unit Cost
      { wch: 10 }, // Cost 2
      { wch: 12 }, // Total Cost
      { wch: 10 }, // Cost 3
      { wch: 10 }, // Cost 4
      { wch: 12 }, // Total Cost 2
      { wch: 8 }, // Value
    ]
    ws["!cols"] = colWidths

    // Style the header row
    const headerStyle = {
      font: { bold: true, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "4472C4" } },
      alignment: { horizontal: "center", vertical: "center" },
    }

    // Apply header styling
    const range = XLSX.utils.decode_range(ws["!ref"] || "A1")
    for (let col = range.s.c; col <= range.e.c; col++) {
      const cellAddress = XLSX.utils.encode_cell({ r: 0, c: col })
      if (!ws[cellAddress]) continue
      ws[cellAddress].s = headerStyle
    }

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(wb, ws, "Warehouse Operations Data")

    // Add metadata sheet
    const metadataSheet = XLSX.utils.json_to_sheet([
      { Property: "Export Date", Value: new Date().toLocaleString() },
      { Property: "Total Records", Value: filteredData.length },
      { Property: "Search Filter", Value: searchTerm || "None" },
      { Property: "Generated By", Value: "Warehouse Costing & Analytics Platform" },
    ])
    XLSX.utils.book_append_sheet(wb, metadataSheet, "Export Info")

    // Generate filename with timestamp
    const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-")
    const filename = `warehouse-operations-data-${timestamp}.xlsx`

    // Use browser-compatible write method
    const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" })
    const blob = new Blob([wbout], { type: "application/octet-stream" })

    // Create download link
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", filename)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-col md:flex-row gap-4 justify-between">
        <div className="flex items-center gap-2 w-full md:w-auto">
          <div className="relative w-full md:w-64">
            <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-8"
            />
          </div>
          <Button variant="outline" size="icon">
            <Search className="h-4 w-4" />
          </Button>
        </div>

        <div className="flex gap-2">
          <Card className="border-blue-200 bg-blue-50">
            <CardHeader className="p-2">
              <CardTitle className="text-xs text-blue-700">
                Recalculate output for all warehouses and updated report pivots
              </CardTitle>
            </CardHeader>
          </Card>
        </div>

        <div className="flex gap-2">
          <Card className="border-blue-200 bg-blue-50">
            <CardHeader className="p-2 flex flex-row items-center gap-2">
              <div className="bg-blue-600 rounded-full w-6 h-6 flex items-center justify-center">
                <RefreshCw className="h-3 w-3 text-white" />
              </div>
              <CardTitle className="text-xs text-blue-700">Display all included</CardTitle>
            </CardHeader>
          </Card>

          <Card className="border-purple-200 bg-purple-50">
            <CardHeader className="p-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleExportToXLS}
                className="flex items-center gap-2 text-purple-700 hover:text-purple-800 hover:bg-purple-100 p-0"
              >
                <div className="bg-purple-600 rounded-full w-6 h-6 flex items-center justify-center">
                  <Download className="h-3 w-3 text-white" />
                </div>
                <CardTitle className="text-xs">Quick Export XLS</CardTitle>
              </Button>
            </CardHeader>
          </Card>

          <EnhancedExportDialog data={warehouseData} filteredData={filteredData} searchTerm={searchTerm} />
        </div>
      </div>

      <div className="rounded-md border overflow-hidden">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader className="bg-blue-100">
              <TableRow>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Storage Type</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Pick Type</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Routing</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Instruction</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Country</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Resource</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Process</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Region</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Identifier</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Unit</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Resource</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Unit Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Total Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Total Cost</TableHead>
                <TableHead className="font-semibold text-blue-800 whitespace-nowrap">Value</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredData.map((row, index) => (
                <TableRow key={index} className={index % 2 === 0 ? "bg-blue-50" : "bg-white"}>
                  <TableCell className="text-sm text-blue-900">{row.storageType}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.pickType}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.routing}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.instruction}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.country}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.resource}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.process}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.region}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.identifier}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.unit}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.cost}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.resource2}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.unitCost}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.cost2}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.totalCost}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.cost3}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.cost4}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.totalCost2}</TableCell>
                  <TableCell className="text-sm text-blue-900">{row.value}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}

// Sample data based on the image
const warehouseData = [
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Blue collar",
    process: "Receiving",
    region: "North West",
    identifier: "1234",
    unit: "1",
    cost: "3.18",
    resource2: "Blue collar",
    unitCost: "25,456.00",
    cost2: "25,456.00",
    totalCost: "25,456.00",
    cost3: "5,620.35",
    cost4: "31,076.35",
    totalCost2: "31,076.35",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Supervisor",
    process: "Receiving",
    region: "North West",
    identifier: "1234",
    unit: "1",
    cost: "4.25",
    resource2: "Supervisor",
    unitCost: "4,564.00",
    cost2: "4,564.00",
    totalCost: "4,564.00",
    cost3: "1,005.35",
    cost4: "5,569.35",
    totalCost2: "5,569.35",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Space",
    process: "Storage",
    region: "North West",
    identifier: "1234",
    unit: "1",
    cost: "253.75",
    resource2: "Space",
    unitCost: "15,742.42",
    cost2: "15,742.42",
    totalCost: "15,742.42",
    cost3: "4,708.36",
    cost4: "20,450.78",
    totalCost2: "20,450.78",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Equipment",
    process: "Storage",
    region: "North West",
    identifier: "1234",
    unit: "1",
    cost: "142.87",
    resource2: "Equipment",
    unitCost: "12,234.54",
    cost2: "12,234.54",
    totalCost: "12,234.54",
    cost3: "3,655.78",
    cost4: "15,890.32",
    totalCost2: "15,890.32",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Energy",
    process: "Storage",
    region: "North West",
    identifier: "1234",
    unit: "1",
    cost: "7,500.00",
    resource2: "Energy",
    unitCost: "7,500.00",
    cost2: "7,500.00",
    totalCost: "7,500.00",
    cost3: "2,250.00",
    cost4: "9,750.00",
    totalCost2: "9,750.00",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Blue collar",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "3.18",
    resource2: "Blue collar",
    unitCost: "15,344.54",
    cost2: "15,344.54",
    totalCost: "15,344.54",
    cost3: "3,386.35",
    cost4: "18,730.89",
    totalCost2: "18,730.89",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Equipment",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.15",
    resource2: "Equipment",
    unitCost: "864.64",
    cost2: "864.64",
    totalCost: "864.64",
    cost3: "646.40",
    cost4: "1,511.04",
    totalCost2: "1,511.04",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Space",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.15",
    resource2: "Space",
    unitCost: "864.64",
    cost2: "864.64",
    totalCost: "864.64",
    cost3: "646.40",
    cost4: "1,511.04",
    totalCost2: "1,511.04",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.15",
    resource2: "Equipment",
    unitCost: "2,477.85",
    cost2: "2,477.85",
    totalCost: "2,477.85",
    cost3: "2,477.85",
    cost4: "4,955.70",
    totalCost2: "4,955.70",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Blue collar",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "7",
    cost: "3.18",
    resource2: "Blue collar",
    unitCost: "10,258.94",
    cost2: "10,258.94",
    totalCost: "10,258.94",
    cost3: "10,258.94",
    cost4: "20,517.88",
    totalCost2: "20,517.88",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.11",
    resource2: "Equipment",
    unitCost: "459.01",
    cost2: "459.01",
    totalCost: "459.01",
    cost3: "459.01",
    cost4: "918.02",
    totalCost2: "918.02",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Space",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.11",
    resource2: "Space",
    unitCost: "459.01",
    cost2: "459.01",
    totalCost: "459.01",
    cost3: "459.01",
    cost4: "918.02",
    totalCost2: "918.02",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.11",
    resource2: "Equipment",
    unitCost: "459.01",
    cost2: "459.01",
    totalCost: "459.01",
    cost3: "459.01",
    cost4: "918.02",
    totalCost2: "918.02",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.11",
    resource2: "Equipment",
    unitCost: "459.01",
    cost2: "459.01",
    totalCost: "459.01",
    cost3: "459.01",
    cost4: "918.02",
    totalCost2: "918.02",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.05",
    resource2: "Equipment",
    unitCost: "2,550.01",
    cost2: "2,550.01",
    totalCost: "2,550.01",
    cost3: "2,550.01",
    cost4: "5,100.02",
    totalCost2: "5,100.02",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Blue collar",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.05",
    resource2: "Blue collar",
    unitCost: "6,860.59",
    cost2: "6,860.59",
    totalCost: "6,860.59",
    cost3: "6,860.59",
    cost4: "13,721.18",
    totalCost2: "13,721.18",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.05",
    resource2: "Equipment",
    unitCost: "3,664.07",
    cost2: "3,664.07",
    totalCost: "3,664.07",
    cost3: "3,664.07",
    cost4: "7,328.14",
    totalCost2: "7,328.14",
    value: "High",
  },
  {
    storageType: "Rack",
    pickType: "Pick 1",
    routing: "1",
    instruction: "01/01",
    country: "Netherlands",
    resource: "Forklift",
    process: "Picking (pick type 1)",
    region: "Central",
    identifier: "1234",
    unit: "4",
    cost: "0.05",
    resource2: "Equipment",
    unitCost: "172.04",
    cost2: "172.04",
    totalCost: "172.04",
    cost3: "172.04",
    cost4: "344.08",
    totalCost2: "344.08",
    value: "High",
  },
]
